CREATE TABLE MEMBER (
    ID VARCHAR2(30) PRIMARY KEY
);

DROP TABLE BOARD;

CREATE TABLE BOARD (
    NO NUMBER,
    TITLE VARCHAR2(50) CONSTRAINT board_nn_title NOT NULL,
    CONTENT VARCHAR2(500) CONSTRAINT board_nn_content NOT NULL,
    WRITER VARCHAR2(30),
    STATUS VARCHAR2(1) DEFAULT 'Y',
    CREATE_DATE DATE DEFAULT SYSDATE,
    UPDATE_DATE DATE DEFAULT SYSDATE,
    CONSTRAINT board_pk_no PRIMARY KEY(NO),
    CONSTRAINT board_ch_status CHECK(STATUS IN ('Y', 'N')),
    CONSTRAINT board_fk_writer FOREIGN KEY(WRITER) REFERENCES MEMBER(ID)
);

COMMENT ON COLUMN BOARD.NO IS '글번호';
COMMENT ON COLUMN BOARD.TITLE IS '제목';
COMMENT ON COLUMN BOARD.CONTENT IS '내용';
COMMENT ON COLUMN BOARD.WRITER IS '작성자';
COMMENT ON COLUMN BOARD.STATUS IS '삭제여부';
COMMENT ON COLUMN BOARD.CREATE_DATE IS '작성일';
COMMENT ON COLUMN BOARD.UPDATE_DATE IS '수정일';

SELECT * FROM BOARD A, MEMBER B WHERE A.WRITER = B.ID AND STATUS = 'Y';