-- 직원관리 계정생성
CREATE USER EMPLOYEE IDENTIFIED BY EMPLOYEE;

GRANT RESOURCE, CONNECT TO EMPLOYEE;


--select * from nls_session_parameters
--        where PARAMETER in  ('NLS_LANGUAGE','NLS_DATE_FORMAT','NLS_DATE_LANGUAGE');

CREATE USER kh IDENTIFIED BY oracle;
GRANT CONNECT, RESOURCE TO kh;
SELECT username from dba_users;
SELECT username, account_status FROM dba_users WHERE username='KH';

-- HOMEWORK 계정 생성
CREATE USER HOMEWORK IDENTIFIED BY HOMEWORK;
GRANT RESOURCE, CONNECT TO HOMEWORK;

GRANT CREATE VIEW TO EMPLOYEE; -- 뷰를 생성할 수 있는 권한 주기

-- SYNONYM 수업
-- SYNONYM 권한 주기
GRANT CREATE SYNONYM TO EMPLOYEE;

SELECT * FROM DBA_SYNONYMS WHERE SYNONYM_NAME = 'EMP'; -- 시스템계정에서 찾아볼 때

-- DBA가 만드는 것이 공개 동의어
SELECT * FROM EMP; -- 에러 발생 비공개 동의어이기 때문에 EMPLYOEE 계정에서만 사용 가능
SELECT * FROM EMPLOYEE.DEPARTMENT;
--SELECT * FROM EMPLOYEE.EMP; -- 이건 됨

CREATE PUBLIC SYNONYM DEPT FOR EMPLOYEE.DEPARTMENT;

DROP PUBLIC SYNONYM "DPET"; -- 삭제 잘못 만들어서 지우는거

SELECT * FROM DEPT;

-- 권한(DCL)과 ROLE 수업
CREATE USER SAMPLE IDENTIFIED BY SAMPLE;
GRANT CREATE SESSION TO SAMPLE; 
GRANT CREATE TABLE TO SAMPLE;

SELECT * 
FROM DBA_USERS 
WHERE USERNAME = 'SAMPLE';

GRANT CREATE SESSION TO SAMPLE
WITH ADMIN OPTION; -- SAMPLE이 다른 사용자에게 권한을 줄 수 있는 권한을 가지게 됨


GRANT SELECT ON EMPLOYEE.EMPLOYEE TO SAMPLE
WITH GRANT OPTION;


CREATE ROLE MYROLE;
GRANT CREATE SESSION, CREATE TABLE TO MYROLE;
GRANT MYROLE TO SAMPLE;

SELECT * FROM USER_ROLE_PRIVS;