-- DDL
-- ALTER : 객체를 수정하는 구문
-- ALTER TABLE 테이블명 수정 내용
-- 컬럼추가 / 삭제 / 변경, 제약조건 추가/삭제
-- 테이블명 변경, 제약조건 이름 변경

-- 컬럼 추가
SELECT * FROM DEPT_COPY;

ALTER TABLE DEPT_COPY
ADD(LNAME VARCHAR(20));

-- 컬럼 삭제
ALTER TABLE DEPT_COPY
DROP COLUMN LNAME;

-- 컬럼 생성시 DEFAULT 값 지정
ALTER TABLE DEPT_COPY
ADD (CNAME VARCHAR2(20) DEFAULT '한국');

-- 제약조건 없이 테이블 생성
CREATE TABLE DEPT_COPY2
AS
SELECT * FROM DEPARTMENT;

-- 컬럼에 제약조건 추가
ALTER TABLE DEPT_COPY2
ADD CONSTRAINT PK_DEPT_ID2 PRIMARY KEY (DEPT_ID);

ALTER TABLE DEPT_COPY2
ADD CONSTRAINT UN_DEPT_TITLE UNIQUE (DEPT_TITLE);

ALTER TABLE DEPT_COPY2
MODIFY LOCATION_ID CONSTRAINT NN_LID NOT NULL;

-- 컬럼 자료형 수정
ALTER TABLE DEPT_COPY2
MODIFY DEPT_ID CHAR(3)
MODIFY DEPT_TITLE VARCHAR2(30)
MODIFY LOCATION_ID VARCHAR2(2);

SELECT * FROM SYS.USER_TAB_COLUMNS WHERE TABLE_NAME = 'DEPT_COPY2';

-- 컬럼의 크기 줄이는 경우
-- 변경하려는 크기를 초과하는 값이 없을때만 수정 가능
ALTER TABLE DEPT_COPY2
MODIFY DEPT_TITLE VARCHAR2(10); -- ORA-01441: cannot decrease column length because some value is too big
-- 01441. 00000 -  "cannot decrease column length because some value is too big"

-- DEFULAT 값 변경
SELECT * FROM DEPT_COPY;

ALTER TABLE DEPT_COPY
MODIFY CNAME DEFAULT '미국';

INSERT INTO DEPT_COPY
VALUES('D0', '생산부', 'L2', DEFAULT);

-- 컬럼 삭제 : DROP COLUMN 삭제할 컬럼명
-- 데이터가 기록되어 있어도 삭제됨
-- 삭제한 컬럼은 복구 불가능
-- 테이블에는 최소 한 개의 컬럼이 존재해야함 : 모든 컬럼 삭제 불가능

ALTER TABLE DEPT_COPY2
DROP COLUMN DEPT_TITLE;

ALTER TABLE DEPT_COPY2
DROP COLUMN LOCATION_ID;

ALTER TABLE DEPT_COPY2
DROP COLUMN DEPT_ID;
-- 마지막 컬럼이라 지울 수 없음
-- cannot drop all columns in a table
-- 12983. 00000 -  "cannot drop all columns in a table"

-- 순환 참조 테이블, 자기 자신 테이블을 참조
CREATE TABLE TB1 (
    PK NUMBER PRIMARY KEY,
    FK NUMBER REFERENCES TB1,
    COL1 NUMBER,
    CHECK (PK > 0 AND COL1 > 0)
);

-- 컬럼 삭제시 참조하고 있는 컬럼이 있다면 삭제 못함
ALTER TABLE TB1
DROP COLUMN PK;
-- ORA-12992: cannot drop parent key column
-- 12992. 00000 -  "cannot drop parent key column"

-- 제약조건도 함께 삭제
ALTER TABLE TB1
DROP COLUMN PK CASCADE CONSTRAINTS;

-- 제약조건 삭제
-- ON DELETE CASCADE : 삭제되는 외부키에 해당하는 행을 같이 삭제 (참조 무결성제약조건)
-- ON DELETE SET NULL : 삭제되는 외부키를 가지는 값을 NULL로 바꿔줌

CREATE TABLE CONST_EMP(
  ENAME VARCHAR2(20) NOT NULL,
  ENO VARCHAR2(15) NOT NULL,
  MARRIAGE CHAR(1) DEFAULT 'N',
  EID CHAR(3),
  EMAIL VARCHAR2(30),
  JID CHAR(2),
  MID CHAR(3),
  DID CHAR(2),
  -- 테이블 레벨로 제약조건 설정
  CONSTRAINT CK_MARRIAGE CHECK(MARRIAGE IN ('Y', 'N')),
  CONSTRAINT PK_EID PRIMARY KEY(EID),
  CONSTRAINT UN_ENO UNIQUE(ENO),
  CONSTRAINT UN_EMAIL UNIQUE(EMAIL),
  CONSTRAINT FK_JID FOREIGN KEY(JID)
  REFERENCES JOB(JOB_CODE) ON DELETE SET NULL,
  CONSTRAINT FK_MID FOREIGN KEY(MID)
  REFERENCES CONST_EMP ON DELETE SET NULL,
  CONSTRAINT FK_DID FOREIGN KEY(DID)
  REFERENCES DEPARTMENT ON DELETE CASCADE
);


-- 제약조건 1개 삭제시
ALTER TABLE CONST_EMP
DROP CONSTRAINT CK_MARRIAGE;

-- 제약조건을 여러개 삭제시
ALTER TABLE CONST_EMP
DROP CONSTRAINT FK_DID
DROP CONSTRAINT FK_JID
DROP CONSTRAINT FK_MID;

-- NOT NULL 제약조건 삭제시 MODIFY 사용
ALTER TABLE CONST_EMP
MODIFY (ENAME NULL, ENO NULL);

-- 컬럼이름 변경
CREATE TABLE DEPT_COPY3
AS SELECT * FROM DEPARTMENT;

ALTER TABLE DEPT_COPY3
RENAME COLUMN DEPT_ID TO DEPT_CODE;

-- 제약조건 이름 변경
ALTER TABLE DEPT_COPY3
ADD CONSTRAINT PK_DEPT_CODE3 PRIMARY KEY (DEPT_CODE);

ALTER TABLE DEPT_COPY3
RENAME CONSTRAINT PK_DEPT_CODE3 TO PK_CODE;

-- 테이블 이름 변경
ALTER TABLE DEPT_COPY3
RENAME TO DEPT_TEST;

SELECT * FROM DEPT_TEST;
SELECT * FROM DEPT_COPY3;

-- 테이블 삭제 CASCADE CONSTRAINT : 삭제할 테이블의 기본키 / UNIQUE 키를 참조하는 제약조건도 함께 삭제
DROP TABLE USER_GRADE2; -- 참조하고 있어서 지울 수 없음
DROP TABLE USER_GRADE2 CASCADE CONSTRAINT;